### ISSUE TITLE
Error occurs

### ISSUE THREAD

**Issue by Vincetes** [xtekky/chatgpt-clone#12] opened 2023-04-23 04:30 UTC
I don't konw why i sent information, it sents"{ "error": { "message": "You exceeded your current quota, please check your plan and billing details.", "type": "insufficient_quota", "param": null, "code": null } }"；Can you tell me what happend,  thank you so much!!!

**Comment by xtekky** [comment] 2023-04-23 18:29
duplicate of #11

**Closed by xtekky** 2023-04-23 18:29 UTC
Labels: duplicate
